---
- src: https://github.com/yusekiya/ansible_role_ubuntu_common
  name: ubuntu_common

- src: https://github.com/yusekiya/ansible_role_nvidia_driver
  name: nvidia_driver

- src: https://github.com/yusekiya/ansible_role_docker
  name: docker

- src: https://github.com/yusekiya/ansible_role_docker_compose
  name: docker_compose

- src: https://github.com/yusekiya/ansible_role_nvidia_docker
  name: nvidia_docker

- src: https://github.com/yusekiya/ansible_role_dev_env
  name: dev_env
