---
docker_required_packages:
  - apt-transport-https
  - ca-certificates
  - gnupg2

docker_repository:
  keyid: '58118E89F3A912897C070ADBF76221572C52609D'
  keyserver: 'hkp://ha.pool.sks-keyservers.net:80'

docker_recommended_packages: []
