---
- include_vars: '{{ansible_lsb.id}}.yml'

- name: Install requirements
  apt:
    name: '{{item}}'
    state: present
  with_items: '{{docker_required_packages}}'
  tags:
    - always

- name: Add the new GPG key
  apt_key:
    id: '{{docker_repository.keyid}}'
    keyserver: '{{docker_repository.keyserver}}'
  tags:
    - always

- name: Add apt repository
  apt_repository:
    repo: 'deb https://apt.dockerproject.org/repo {{ ansible_lsb.id | lower }}-{{ ansible_distribution_release }} main'
    update_cache: yes
  tags:
    - always

- name: Update cache
  apt:
    update_cache: yes
  tags:
    - always

- name: Install recommended packages
  apt:
    name: '{{item}}'
    state: present
  with_items: '{{docker_recommended_packages}}'
  tags:
    - recommended

- name: Install docker
  apt:
    name: docker-engine
    state: latest
    update_cache: yes
  tags:
    - always

- name: Start docker service and enable/disable it on boot
  service:
    name: docker
    state: started
    enabled: '{{docker_service_enabled}}'
  tags:
    - always

- name: Create docker group
  group:
    name: docker
  tags:
    - optional

- name: Configure DNS server for docker
  lineinfile:
    state: present
    dest: /etc/default/docker
    regexp: '^#?DOCKER_OPTS'
    line: 'DOCKER_OPTS="--dns 8.8.8.8"'
  notify: Restart docker
  tags:
    - optional

- name: Install docker compose
  get_url:
    url: https://github.com/docker/compose/releases/download/{{docker_compose_version}}/docker-compose-{{ansible_system}}-{{ansible_architecture}}
    dest: /usr/local/bin/docker-compose
    mode: 0755
    owner: root
    group: root
  when: ansible_architecture == 'x86_64'
  tags:
    - docker_compose
