---
- name: Install requirements
  apt:
    name: '{{item}}'
    state: present
  with_items:
    - apt-transport-https
    - ca-certificates
  tags:
    - always

- name: Add the new GPG key
  apt_key:
    id: '58118E89F3A912897C070ADBF76221572C52609D'
    keyserver: 'hkp://p80.pool.sks-keyservers.net:80'
  tags:
    - always

- name: Add apt repository
  apt_repository:
    repo: 'deb https://apt.dockerproject.org/repo {{ ansible_lsb.id | lower }}-{{ ansible_distribution_release }} main'
    update_cache: yes
  tags:
    - always

- name: Update cache
  apt:
    update_cache: yes
  tags:
    - always

- name: Install recommended packages
  apt:
    name: '{{item}}'
    state: present
  with_items:
    - 'linux-image-extra-{{ansible_kernel}}'
    - linux-image-extra-virtual
  tags:
    - recommended

- name: Install docker
  apt:
    name: docker-engine
    state: latest
    update_cache: yes
  tags:
    - always

- name: Start docker service and enable/disable it on boot
  service:
    name: docker
    state: started
    enabled: '{{docker_service_enabled}}'
  tags:
    - always

- name: Create docker group
  group:
    name: docker
  tags:
    - optional

- name: Configure DNS server for docker
  lineinfile:
    state: present
    dest: /etc/default/docker
    regexp: '^#?DOCKER_OPTS'
    line: 'DOCKER_OPTS="--dns 8.8.8.8"'
  notify: Restart docker
  tags:
    - optional

- name: Install docker compose
  get_url:
    url: https://github.com/docker/compose/releases/download/{{docker_compose_version}}/docker-compose-{{ansible_system}}-{{ansible_architecture}}
    dest: /usr/local/bin/docker-compose
    mode: 0755
    owner: root
    group: root
  tags:
    - docker_compose
