---
- name: Change timezone
  template:
    src: timezone.j2
    dest: /etc/timezone
    owner: root
    group: root
    mode: 0644
  notify: Update timezone
  tags:
    - timezone

- name: Change hostname [/etc/hostname]
  template:
    src: hostname.j2
    dest: /etc/hostname
    owner: root
    group: root
    mode: 0644
  tags:
    - hostname

- name: Change hostname [/etc/hosts]
  lineinfile:
    state: present
    dest: /etc/hosts
    backrefs: yes
    regexp: '^127\.0\.1\.1'
    line: '127.0.1.1 {{ ubuntu_common_hostname }}'
  tags:
    - hostname

- name: Update package index file
  apt: update_cache=yes

- name: Install packages
  apt:
    name: '{{ item.name }}'
    state: '{{ item.state | default("latest") }}'
  with_items: '{{ ubuntu_common_packages }}'
  tags:
    - apt
